namespace SmsHub.Persistence.Migrations.Enums
{
    internal enum TableName
    {
        User,
        UserLogin,
        Role,
        UserRole,
        UserToken,
        InvalidLoginReason,
        LogoutReason,
        Provider,
        Line,
        UserLine,
        Consumer,
        ConsumerLine,
        ConsumerSafeIp,
        ContactCategory,
        ContactNumberCategory,
        Contact,
        ContactNumber,
        TemplateCategory,
        UserTemplateCategory,
        Template,
        MessageBatch,
        MessagesHolder,
        MessageDetail,
        MessageDetailStatus,
        MessageStateCategory,
        MessageState,
        Received,
        ReceivedHolder,//todo
        ReceivedDetails,//todo
        LogLevel,
        InformativeLog,
        OperationType,
        DeepLog,
        ConfigTypeGroup,
        PermittedTime,
        DisallowedPhrase,
        CcSend,
        Config,//todo
        //todo: cost tables
        ServerUser,
        ProviderResponseStatus,
        ProviderDeliveryStatus,

        HttpLog
    }
}
